// Dummy data for UI testing - will be replaced with Sanity data when credentials are available
// Set USE_DUMMY_DATA=true in .env.local to use this data

export const dummyBlogs = [
  {
    _id: "blog-1",
    title: "Finding Faith in Difficult Times",
    author: "John Smith",
    publishedAt: "2026-01-10T10:00:00Z",
    category: "faith",
    excerpt: "Discover how to strengthen your faith when facing life's greatest challenges.",
    image: { asset: { url: "/bib-4.jpg" } },
    slug: { current: "finding-faith-difficult-times" },
  },
  {
    _id: "blog-2",
    title: "The Power of Community Worship",
    author: "Sarah Johnson",
    publishedAt: "2026-01-08T14:30:00Z",
    category: "community",
    excerpt: "Explore how worshipping together strengthens our bonds and deepens our connection.",
    image: { asset: { url: "/bible-1.jpg" } },
    slug: { current: "power-community-worship" },
  },
  {
    _id: "blog-3",
    title: "Biblical Principles for Daily Living",
    author: "Michael Chen",
    publishedAt: "2026-01-05T09:15:00Z",
    category: "devotional",
    excerpt: "Learn how to apply biblical wisdom to your everyday decisions and challenges.",
    image: { asset: { url: "/bible-2.jpg" } },
    slug: { current: "biblical-principles-daily-living" },
  },
];

export const dummySermons = [
  {
    _id: "sermon-1",
    title: "The Foundation of Faith",
    speaker: "Pastor John",
    date: "2026-01-05T10:00:00Z",
    series: "Foundations",
    excerpt: "Discover what it means to build your life on the solid foundation of faith in Jesus Christ.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    slug: { current: "foundation-of-faith" },
  },
  {
    _id: "sermon-2",
    title: "Living in Victory",
    speaker: "Pastor Sarah",
    date: "2025-12-29T10:00:00Z",
    series: "Victory in Christ",
    excerpt: "Learn how to live victoriously through Christ in every circumstance of life.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    slug: { current: "living-in-victory" },
  },
  {
    _id: "sermon-3",
    title: "The Power of Prayer",
    speaker: "Pastor Michael",
    date: "2025-12-22T10:00:00Z",
    series: "Prayer",
    excerpt: "Unlock the transformative power of prayer and see God work in your life.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    slug: { current: "power-of-prayer" },
  },
];

export const dummyEvents = [
  {
    _id: "event-1",
    title: "Sunday Worship",
    startDate: "2026-01-12T10:00:00Z",
    location: "Main Sanctuary",
    category: "worship",
    description: "Join us for our weekly Sunday worship service with inspiring music and teaching.",
    ministry: "ministry-5",
  },
  {
    _id: "event-2",
    title: "Bible Study",
    startDate: "2026-01-14T19:00:00Z",
    location: "Fellowship Hall",
    category: "study",
    description: "Deep dive into Scripture with our community.",
    ministry: "ministry-2",
  },
  {
    _id: "event-3",
    title: "Youth Group",
    startDate: "2026-01-16T18:00:00Z",
    location: "Youth Center",
    category: "youth",
    description: "Fun activities and spiritual growth for young people.",
    ministry: "ministry-1",
  },
  {
    _id: "event-4",
    title: "Community Service",
    startDate: "2026-01-18T09:00:00Z",
    location: "Community Center",
    category: "community",
    description: "Serve our community together.",
    ministry: "ministry-6",
  },
];

export const dummyMinistries = [
  {
    _id: "ministry-1",
    title: "Youth Ministry",
    description: "Empowering young people to grow in faith, build meaningful relationships, and discover their purpose in Christ.",
    icon: "Smile",
    image: "/bible-1.jpg",
    highlights: [
      "Weekly youth group meetings with engaging activities",
      "Mentorship programs pairing youth with mature believers",
      "Mission trips and community service opportunities",
      "Leadership development and discipleship training",
    ],
    ctaLabel: "Get Involved",
    ctaHref: "/contact",
    order: 1,
  },
  {
    _id: "ministry-2",
    title: "Women's Ministry",
    description: "A supportive community where women grow together in faith, encourage one another, and live out their calling.",
    icon: "Heart",
    image: "/bible-2.jpg",
    highlights: [
      "Bible studies and prayer groups for spiritual growth",
      "Mentorship and discipleship programs",
      "Community service and outreach initiatives",
      "Conferences and spiritual retreats",
    ],
    ctaLabel: "Join Us",
    ctaHref: "/contact",
    order: 2,
  },
  {
    _id: "ministry-3",
    title: "Children's Ministry",
    description: "Creating a safe, nurturing environment where children learn about Jesus and grow in their faith journey.",
    icon: "Baby",
    image: "/bib-4.jpg",
    highlights: [
      "Age-appropriate Sunday school classes",
      "Vacation Bible School during summer",
      "Children's worship and activities",
      "Parent resources and family events",
    ],
    ctaLabel: "Enroll",
    ctaHref: "/contact",
    order: 3,
  },
  {
    _id: "ministry-4",
    title: "Men's Ministry",
    description: "Building strong men of faith through fellowship, accountability, and spiritual growth.",
    icon: "Users",
    image: "/bible-1.jpg",
    highlights: [
      "Monthly men's breakfast and fellowship",
      "Bible study and prayer groups",
      "Service projects and outreach",
      "Mentorship and discipleship opportunities",
    ],
    ctaLabel: "Join Us",
    ctaHref: "/contact",
    order: 4,
  },
  {
    _id: "ministry-5",
    title: "Worship Ministry",
    description: "Leading the church in worship through music, prayer, and creating an atmosphere for encountering God.",
    icon: "Lightbulb",
    image: "/bible-2.jpg",
    highlights: [
      "Choir and worship band opportunities",
      "Sound and technical support",
      "Worship training and development",
      "Special music and performances",
    ],
    ctaLabel: "Participate",
    ctaHref: "/contact",
    order: 5,
  },
  {
    _id: "ministry-6",
    title: "Community Outreach",
    description: "Extending God's love to our community through service, compassion, and practical help.",
    icon: "MessageSquare",
    image: "/bib-4.jpg",
    highlights: [
      "Partnership with local organizations",
      "Food bank and clothing distribution",
      "Community events and festivals",
      "Disaster relief and emergency assistance",
    ],
    ctaLabel: "Serve",
    ctaHref: "/contact",
    order: 6,
  },
];
